### ISSUE TITLE
Add the URL for Student Portal and Admin Portal in Readme.md

### ISSUE THREAD

**Issue by saviourcode** [DhruvGodambe/smartfeedback#1]
Developers, you might consider mentioning the Fully-Qualified Domain Name of these in the Readme.md file.
- [x] Specify the URL for Student Portal.

- [x] Specify the URL for Admin Portal.  

P.S. Mention the port number as well.

**Comment by DhruvGodambe** [comment]
I have added the the details in the readme.md file as suggested
